language: node_js
node_js: '0.10'
before_script:
- npm install -g grunt-cli
- npm install -g bower
- npm install
- bower install
script:
- grunt travis
env:
  global:
  - secure: W5vbUYV3APtbtMw+dcogNIAB+G90nO9XTjYRBCkBMmRWOBAWan2BG3/9azENq6RHa8+J9fxd2VK/kcUz9sHTCezY1SfsUHmEKBR9/RiqFHi3HpucaLpqncGURvvAbwKCXmVnCbmEVBY6GCgQn2R/7bHEjp/gdFy7Q3oojnOtB4Q=
  - secure: XTEd9KZ38uk0I+HfamlqGfmuKXFXu62IJVGEbO4A2IKt/GFyNRoDiXEhGuOZgvlccl3tjkigO7paNyC4C8KjFPbjI8aGuLvBQiT4YfeXRIWFRKGdsTLPZttMwUQ8tCXgRZ1eGJP+X6gVTLnJF4Jvk4wsoq0pQQAvKXDGClrcue4=
  - secure: c/dHGRCWmPjwUJ/Cl9tlqFLXS7ZlIK0uORzaCQdTDakuBJXs1KbKehryLKWekThoXNyWqBujANaSieePcAm5YwLgfkTZl1Gk5TVxAiyG1/4hpW53esQvHh53qrMD6aQTJvx333ih+Xh2MeRwU5CQs6QEKCq692duvFack4a86oY=
  - secure: iS8HGzC/5DwV4Jy1l0DgvxxS9NaHAHtEvWK1qpebH91/Bick8dFtAHAjKNC5Ool/wNZUSZHfLZPt9YwyxL9/Zq3kMxF0UkfZ3mdJkweRS7qiMN2/oKVWv5yvjkHLM0/rBEpGF7prYCcCtjM1VYBXm0AfqIWGitPEXH+0J2spLwc=
